import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/component/Navbar";
import Authprovider from "./components/auth/authprovider";
const inter = Inter({ subsets: ["latin"] });
import { useState,useEffect } from "react";
import { useSession } from "next-auth/react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
          <Navbar />
          {children}
        </Authprovider>
      </body>
    </html>
  );
}
